[functions]
  directory = "src"
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/"
[build]
  command = "echo 'default context'"